(ql:quickload :clunit)

(defpackage :cl-etudes.life-test
  (:use :common-lisp :cl-etudes.life :clunit)
  (:shadow :run)
  (:export :run))

(in-package :cl-etudes.life-test)

(defsuite life-test-suite ())

(deftest test-neighbors (life-test-suite)
  (let* ((field-data '((0 0 0 0 0)
                       (0 0 0 0 0)
                       (0 0 1 0 0)
                       (0 0 0 0 0)
                       (0 0 0 0 0)))
         (field (make-array '(5 5) :initial-contents field-data))
         (neighbors-map '((0 0 0 0 0)
                          (0 1 1 1 0)
                          (0 1 0 1 0)
                          (0 1 1 1 0)
                          (0 0 0 0 0)))
         (frame '((0 0 0 0 0)
                  (0 0 0 0 0)
                  (0 0 0 0 0)
                  (0 0 0 0 0)
                  (0 0 0 0 0))))
    (assert-equalp
        (cl-etudes.life::calculate-neighbors-field field)
        (make-array '(5 5) :initial-contents neighbors-map))
    (assert-equalp
        (cl-etudes.life::next-frame field)
        (make-array '(5 5) :initial-contents frame))))

(deftest test-step (life-test-suite)
  (let* ((field-data '((0 0 0 0 0)
                       (0 0 1 0 0)
                       (0 0 1 0 0)
                       (0 0 1 0 0)
                       (0 0 0 0 0)))
         (field (make-array '(5 5) :initial-contents field-data))
         (neighbors-map '((0 1 1 1 0)
                          (0 2 1 2 0)
                          (0 3 2 3 0)
                          (0 2 1 2 0)
                          (0 1 1 1 0)))
         (frame '((0 0 0 0 0)
                  (0 0 0 0 0)
                  (0 1 1 1 0)
                  (0 0 0 0 0)
                  (0 0 0 0 0)))
         (expected (make-array '(5 5) :initial-contents frame)))
    (assert-equalp
        (make-array '(5 5) :initial-contents neighbors-map)
        (cl-etudes.life::calculate-neighbors-field field))
    (assert-equalp expected (cl-etudes.life::next-frame field))))


(defun run(&optional use-debugger)
  (run-suite 'life-test-suite :use-debugger use-debugger))
